name: pull-intens-api

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: run-tests
        run: mvn test
